export const GET_A_PARTICULAR_USER = "GET_A_PARTICULAR_USER";
export const GET_MY_SELF = 'GET_MY_SELF';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_DETAILS = 'UPDATE_DETAILS';
export const FOLLOW_A_USER = 'FOLLOW_A_USER';
export const SEARCH_USERS = 'SEARCH_USERS';